name: Deploy and Validate Metadata

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Salesforce CLI (sf)
        run: |
          npm install --global @salesforce/cli

      - name: Install Salesforce CLI (SFDX)
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          echo "$HOME/.local/sfdx/bin" >> $GITHUB_PATH

      - name: Verify Salesforce CLI
        run: sfdx --version

      - name: Install sfdx-git-delta plugin
        run: |
          sfdx plugins:install sfdx-git-delta
      
      - name: Authentification Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
        run: |
          echo $SF_AUTH_URL > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias myOrg --set-default

      - name: Generate metadata delta using sfdx-git-delta
        run: |
          mkdir -p .temp
          sf sgd source delta --to "HEAD" --from "origin/main" --output .temp --generate-delta

      - name: Deploy metadata to Salesforce
        if: github.ref == 'refs/heads/main'
        run: |
          sf project deploy start --manifest .temp/package/package.xml --target-org myOrg --check-only --ignore-warnings